### ISSUE TITLE
No links found with Quasar

### ISSUE THREAD

**Issue by Zero0Q** [mancuniancol/script.quasar.magnetic#1]
I get no links found with any magnet providers only with Quasar, with Torrenter it works. Any ideas..

**Comment by mancuniancol** [comment]
Yes, what is your time out? You need more than 1min, start with one provider and check if it gives links.

**Comment by Zero0Q** [comment]
I tried 60 seconds and 120 seconds all of them, one by one. No luck

**Comment by mancuniancol** [comment]
You configured Quasar time out to 60 s. And in magnetic just enabled one provider and it doesn't work? That is weird. Could you share your log with pastebin.com? I can confirm that is working perfectly. And it should work with one provider enabled.

**Comment by Zero0Q** [comment]
This is the log.
https://pastee.org/c5fjp

**Comment by mancuniancol** [comment]
In your log, I see that you have magnetic installed and Quasar, but I don't see any of the test that you said failed

**Comment by Zero0Q** [comment]
That's from before test. I will do other soon..

**Comment by mancuniancol** [comment]
I will close this issue, because I didn't get any more information
