### ISSUE TITLE
Error installing script.module.magnetic on ARMv7 RPI2 + Krypton

### ISSUE THREAD

**Issue by MattMuffin** [mancuniancol/script.quasar.magnetic#2]
Hello,

I get this Python error:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.error'>
                                            Error Contents: [Errno 98] Address already in use
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.module.magnetic/service.py", line 46, in <module>
                                                server = ThreadedHTTPServer((PROVIDER_SERVICE_HOST, PROVIDER_SERVICE_PORT), ProvidersHandler)
                                              File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
                                                self.server_bind()
                                              File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
                                                SocketServer.TCPServer.server_bind(self)
                                              File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
                                                self.socket.bind(self.server_address)
                                              File "/usr/lib/python2.7/socket.py", line 224, in meth
                                                return getattr(self._sock,name)(*args)
                                            error: [Errno 98] Address already in use
                                            -->End of Python script error report<--

I've tested on Ubuntu, I dont have this error; it only appears on the RPi2 / ARMv7 architecture.

Thank you

**Comment by mancuniancol** [comment]
That error means that something else is running with the same port than magnetic.  You need to identify which is that process.

Btw, it is the wrong repository.  You're having problem with [script.module.magnetic](https://github.com/mancuniancol/script.module.magnetic). Not with the connector to Quasar.

**Comment by mancuniancol** [comment]
Any case, you can change the magnetic port changing the number in the line 21 of [utils.py](https://github.com/mancuniancol/script.module.magnetic/blob/master/resources/lib/utils.py) file.

`PROVIDER_SERVICE_PORT = 5005`

**Comment by MattMuffin** [comment]
Thanks! Sory about the wrong repo!

**Comment by MattMuffin** [comment]
Moved to the other repo
